### ISSUE TITLE
User can reset their password

### ISSUE THREAD

**Issue by tan-at** [APUOPE-RE/Wiki#12]
### Description
As a user, I want be able to reset my password if I forget it, so that I can access the tool.

**Acceptance criteria**

- The login form has an option for resetting the user's password.
- The password reset form has a field for user's email.
- A password reset button is located below the form.
- If the app finds a user registered with the email input by the user, the email is sent a link for resetting the user's password. Otherwise nothing is done.

### Specification

**Sign in form**
- [ ] Form has an email field.
- [ ] Form has a reset password button that submits the form for validation.
- [ ] Form checks that the new password conforms to basic standards of a strong password.

Subtasks:

- [ ] APUOPE-RE/frontend#15
- [ ] APUOPE-RE/backend#14

**Comment by roosavihlman** [comment]
Wiki address: https://github.com/APUOPE-RE/Wiki/wiki/FR-%E2%80%90-Password-reset
