### ISSUE TITLE
Write down user stories based on requirements

### ISSUE THREAD

**Issue by williamirva** [APUOPE-RE/Wiki#4]

**Comment by ErickSch** [comment]
As a teacher, I want be able to login with my credentials, so that only I can see information regarding the students.

**Comment by ErickSch** [comment]
As a teacher, I want to be able to select topics to generate a quiz about, so that I dont have to spend time developing te questions and options.

**Comment by ErickSch** [comment]
As a teacher, I want to be able to see student's learning progress, so that I can see teaching effectiveness.

**Comment by ErickSch** [comment]
As a student, I want to be able to have a conversation with a chatbot, so that I can solve questions about the course.

**Comment by tan-at** [comment]
Added user stories for the user to interact with the AI chat:
#27 User can start a new conversation
#28 User can view old conversations
#29 User can continue an old conversation
#30 User can delete an old conversation
